### PR TITLE
Fix mirror hostname for new repo-itb host (SOFTWARE-3465)

### PR DESCRIPTION
**Pull request by edquist**

### CODE REVIEW

**Comment by brianhlin** [comment]
I'm not in love with this in case UNL decides to run the ITB from a different host. Is there a consistent way to do an external name server lookup? If not, I'd prefer that we determine if it's an ITB host based on config.

**Comment by edquist** [comment]
> I'm not in love

valentine's day's not till tmrw, after all.

But yeah neither am i with the hardcoded hostname.

I think the problem is, the unl hostname _is_ the external one -
```
[edquist@mystras ~]$ resolve repo-itb.opensciencegrid.org
129.93.244.200
[edquist@mystras ~]$ resolve 129.93.244.200
hcc-osg-software2.unl.edu
```

That, and in the moment i didn't feel like looking up how to do dns resolution in python :-p

I suppose the best way to do it is just see if hostname->ip == repo-itb.opensciencegrid.org->ip

**Comment by brianhlin** [comment]
Can we just dump this in config somewhere instead?

**Comment by edquist** [comment]
The mirror script doesn't have a config file currently, but if we wanted to add one, we'd either need to (1) configure it manually on repo-itb, or (2) make a separate osg-repo-scripts rpm for repo-itb.

Doing it based on the hostname avoids needing either of those manual steps.

**Comment by edquist** [comment]
I think the update in f133a93 is pretty straightforward and should continue to work as long as repo-itb.opensciencegrid.org resolves to our repo-itb host.

**Comment by brianhlin** [comment]
Wouldn't this break if the host didn't have an external network interface, e.g. if it were behind a NAT? I think what I'm getting at is that I really prefer this sort of thing living in configuration instead of trying to automatically detect it.

**Comment by edquist** [comment]
> what about NAT

So, yeah if it is behind a nat _and_ hostname returns a hostname that resolves to a private (natted) ip address, then yes it will break, but only for repo-itb.  (But note also that the osg-release-itb package has been broken since at least the move away from grid.iu - nobody uses it except us internal folks for testing these rare structural changes to the repos like now.)

But if repo-itb is behind a nat but hostname reports (eg) a unl hostname that resolves to an external ip, then i think this will continue to work.

I'm not sure which would be the case in our scenario where repo-itb moves behind a nat.

Is repo-itb potentially moving behind a nat a possibility anytime soon?

Again, if you want a config setting, this needs to be manually set at install time or else we need to make a separate osg-repo-scripts rpm for repo-itb.  Would you like to go with one of these, or for now are you ok with it as-is with the working assumption that repo-itb reports a hostname that resolves to an external ip?

**Comment by djw8605** [comment]
Repo-itb will not go behind a NAT.  Especially with the admins here unnatural hatred of NATs.

But, it is very likely that all the IP's on the host will be private.  But that an external service will map a public IP onto it.  That's how, for example, docker, kubernetes and openstack work.  The ip on the interface is not the "public" ip.

Though, generally, I would hope the system hostname would be correct.

**Comment by brianhlin** [comment]
> Though, generally, I would hope the system hostname would be correct.

This is the important part (or at least the part that this PR currently depends on), right? That the system hostname resolves to the external IP, which should be the same IP that the ITB host resolves to.

> Again, if you want a config setting, this needs to be manually set at install time or else we need to make a separate osg-repo-scripts rpm for repo-itb.

By "at install time" do you mean that the config has to be placed down before the installation? Or is this just like any other package where we install, configure, then start the service? I think the latter would be what we should be striving for.

**Comment by edquist** [comment]
Thanks @djw8605 for the ops insights!

>it is very likely that all the IP's on the host will be private

>I would hope the system hostname would be correct

So i guess the/my question is whether we'd be able to use the (hopefully correct) system hostname to resolve a public ip that matches whatever repo-itb.opensciencegrid.org resolves to.

Currently it works anyway:

```
[edquist@mystras ~]$ ssh repo-itb
Last login: Wed Feb 13 15:16:39 2019 from mystras.cs.wisc.edu
[osgcollab@hcc-osg-software2 ~]$ python
Python 2.7.5 (default, Apr 11 2018, 07:36:10) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-28)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> def host2ip(name):
...     return socket.getaddrinfo(name, 80, socket.AF_INET)[0][4][0]
... 
>>> import socket
>>> 
>>> socket.gethostname()
'hcc-osg-software2.unl.edu'
>>> 
>>> host2ip(socket.gethostname())
'129.93.244.200'
>>> 
>>> host2ip(socket.gethostname()) == host2ip("repo-itb.opensciencegrid.org")
True
```

@djw8605, do you think the IP's on the host becoming private would break this?

Or better yet, is there any hope for the system hostname to just report xyz.opensciencegrid.org?

**Comment by edquist** [comment]
>This is the important part (or at least the part that this PR currently depends on), right? That the system hostname resolves to the external IP, which should be the same IP that the ITB host resolves to.

Yes, or at any rate this PR expects that the system hostname for repo-itb will resolve to the same IP as repo-itb.opensciencegrid.org

>"at install time"

By that i meant, if we start using a config file, presumably the rpm would lay it down.  If we continue to do a single osg-repo-scripts rpm to be used for both repo & repo-itb, then for the repo-itb host, after yum installing osg-repo-scripts, that config file would need to be edited to get the mirrorlist working properly on repo-itb.

>just like any other package where we install, configure, then start the service

I thought one goal of the opsie packages was as little manual configuration as possible.  So if it's possible to reliably get the information we care about from the environment i'd just as soon skip making it configurable.

... Adding a configuration system to the update mirror script kinda seemed like more work than necessary to make our very-rarely-used use case of installing out of osg-release-itb "robust" against potential future changes.

But yeah if the current proposal hostname/ip base solution does not seem like something that will hold up if IPs go private, then we can add a file for configuring the mirrorlist hostname.

**Comment by edquist** [comment]
UTS name as in `uname -n` ?  (that returns hcc-osg-software2.unl.edu, which i guess was rejected earlier)

**Comment by bbockelm** [comment]
Let’s fix the UTS name on the host then - or, at least, in the systemd service (can be set on a per-service basis).

**Comment by edquist** [comment]
I'm not sure how to configure this.

Although if we're talking about something like editing /etc/hostname, or at any rate something that will make gethostname return repo-itb.opensciencegrid.org, then we can just close this PR as the existing code will work.

**Comment by bbockelm** [comment]
Right - this is something Nebraska should do in the Puppet config (or a Docker config, if that route is eventually taken).

**Comment by matyasselmeci** [comment]
What's gonna happen with this PR? Merge it? Reject it? Save it for later?

**Comment by edquist** [comment]
I think it will remain as a reminder for us (Nebraska) to implement at some point in the future, but in the mean time I think the current PR should not be merged as-is.

**Comment by matyasselmeci** [comment]
repo is now running in Kubernetes so I'm not sure this PR is relevant anymore.

**Pull request closed without merging**
