### PR TITLE
Change services from cron jobs to timed services

### PR DESCRIPTION
**Pull request by hzhu16**

### CODE REVIEW

**Comment by edquist** [comment]
Hi @hzhu16,

I noticed you updated things to leave all logging to stdout/stderr, which I guess goes to syslog (?), instead of writing to their original log files.

I don't have a clear preference but I'll just mention it here that in the past the repo log dir was one place to quickly check that all the repo stuff was running without errors (the log files have recent timestamps and the .err files are all empty).  I presume we'd have to query each systemd service for its log separately.  And I forget how to distinguish between stdout and stderr.

**Comment by hzhu16** [comment]
Now the services write logs to both syslog and /var/log/repo. 
Scripts /opt/service-monitor/repo/test.sh and /usr/local/awstats/wwwroot/cgi-bin/awstats.pl are called as cron jobs (/etc/cron.d/repo), but they are not included in the rpm created by this repository. Why?

**Comment by edquist** [comment]
> Scripts /opt/service-monitor/repo/test.sh and /usr/local/awstats/wwwroot/cgi-bin/awstats.pl are called as cron jobs (/etc/cron.d/repo), but they are not included in the rpm created by this repository. Why?

Hi @hzhu16, yeah I think that service monitor / awstats stuff was in the repo cron.d file for historical reasons that do not exist anymore.  There is a [test.sh](https://github.com/opensciencegrid/osg-repo-scripts/blob/v1.4/opt/service-monitor/repo/test.sh) script that is somehow tied in to this but I don't believe it is relevant anymore either.

So, my recommendation is we drop `test.sh` (which is the only thing under `opt`), and also drop the service monitor and awstats items from the repo crontab.

**Comment by edquist** [comment]
One thing I have mixed feelings about (but not enough to request changes at the moment) is the way we are doing the service commands, eg:
```
[Service]
ExecStart=/bin/bash -c "(/usr/bin/update_all_repos.sh | tee /var/log/repo/update_all_repos.log) 2> >(tee /var/log/repo/update_all_repos.err)" 
```

It is a complex enough command that these might even be better built into a separate script, to avoid having to cram it all into `ExecStart`.  (But maybe we can do that later.)

Also a small note about this part:
```
(XYZ.sh | tee XZY.log) 2> >(tee XYZ.err)
```

This does send stdout to the .log and stderr to .err, but then the copies of both end up in the stdout of the bash command.  I guess this is fine if (as I gather is the case) the stdout and stderr for systemd commands end up logged in the same place for journalctl, rather than kept separately.  But if systemd tracked stdout and stderr separately (eg, hilighted stderr in red or something), then I would suggest sending the tee output for stderr back to stderr, rather than stdout, with something like this instead:
```
(XYZ.sh | tee XZY.log) 2> >(tee XYZ.err >&2)
```
(But, you don't have to make that change if systemd doesn't distinguish between stdout and stderr for logging.)

**Comment by djw8605** [comment]
I've lost track of this.  Should it be merged?  I think it is running in production, correct?

**Comment by edquist** [comment]
I do not believe it is running anywhere.  (Is it???)

I think there were still a couple unaddressed items like dropping `test.sh`.

**Comment by hzhu16** [comment]
It’s running on hcc-osg-repo.unl.edu<http://hcc-osg-repo.unl.edu>

Huijun Zhu
Holland Computing center
huijun.zhu@unl.edu<mailto:huijun.zhu@unl.edu>



On Nov 8, 2019, at 1:10 PM, edquist <notifications@github.com<mailto:notifications@github.com>> wrote:


I do not believe it is running anywhere. (Is it???)

I think there were still a couple unaddressed items like dropping test.sh.

**Comment by matyasselmeci** [comment]
repo is now running in a container which means we can't use systemd timers, so I'm going to close this.

**Pull request closed without merging**
